import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import HomeSlider from '@/components/HomeSlider'


//dummy
import cardThumb1 from "../assets/cardThumb.webp";
import cardThumb2 from "../assets/cardThumb2.webp";
import cardThumb3 from "../assets/cardThumb3.webp";
import cardThumb4 from "../assets/cardThumb4.webp";
import cardThumb5 from "../assets/cardThumb5.webp";
import ProductCard from '@/components/ProductCard';
import SubHeading from '@/components/SubHeading';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>One2Kid</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeSlider/>
        {/* Trending */}
        <div className=' my-20'>
            <SubHeading title={'Trending'} />
            <div className='grid md:grid-cols-5 gap-6'>
                <ProductCard image={cardThumb1}/>
                <ProductCard image={cardThumb2}/>
                <ProductCard image={cardThumb3}/>
                <ProductCard image={cardThumb4}/>
                <ProductCard image={cardThumb5}/>
            </div>
        </div>

        {/* All products */}
        <div className=' my-20'>
            <SubHeading title={'Pick The Best Item'} />
            <div className='grid md:grid-cols-5 gap-6'>
                <ProductCard image={cardThumb1}/>
                <ProductCard image={cardThumb2}/>
                <ProductCard image={cardThumb3}/>
                <ProductCard image={cardThumb4}/>
                <ProductCard image={cardThumb5}/>
                <ProductCard image={cardThumb1}/>
                <ProductCard image={cardThumb2}/>
                <ProductCard image={cardThumb3}/>
                <ProductCard image={cardThumb4}/>
                <ProductCard image={cardThumb5}/>
            </div>
            <div className='flex justify-center'><a href="#" className='btn my-5 rounded-none bg-black'>Show More</a></div>
        </div>
      </main>
    </>
  )
}
